# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 507)
        MainWindow.setFixedSize(337,507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 321, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(36)
        self.outputlabel.setFont(font)
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputlabel.setLineWidth(2)
        self.outputlabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setIndent(3)
        self.outputlabel.setObjectName("outputlabel")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("1"))
        self.pushButton1.setGeometry(QtCore.QRect(13, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("2"))
        self.pushButton_2.setGeometry(QtCore.QRect(93, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("3"))
        self.pushButton_3.setGeometry(QtCore.QRect(173, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("4"))
        self.pushButton_4.setGeometry(QtCore.QRect(251, 90, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("9"))
        self.pushButton_9.setGeometry(QtCore.QRect(92, 250, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")

        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.backbutton())
        self.pushButton_back.setGeometry(QtCore.QRect(12, 250, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")

        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("0"))
        self.pushButton_0.setGeometry(QtCore.QRect(172, 250, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")

        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.result())
        self.pushButton_equal.setGeometry(QtCore.QRect(250, 250, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setObjectName("pushButton_equal")
        

        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.sign("-"))
        self.pushButton_minus.setGeometry(QtCore.QRect(92, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")

        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.sign("+"))
        self.pushButton_plus.setGeometry(QtCore.QRect(12, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName("pushButton_plus")

        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.sign("*"))
        self.pushButton_multiply.setGeometry(QtCore.QRect(172, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setObjectName("pushButton_multiply")

        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.sign("/"))
        self.pushButton_divide.setGeometry(QtCore.QRect(250, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName("pushButton_divide")

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("6"))
        self.pushButton_5.setGeometry(QtCore.QRect(92, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("5"))
        self.pushButton_6.setGeometry(QtCore.QRect(12, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("7"))
        self.pushButton_7.setGeometry(QtCore.QRect(172, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("8"))
        self.pushButton_8.setGeometry(QtCore.QRect(250, 170, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")

        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.pressbutton("C"))
        self.pushButton_clear.setGeometry(QtCore.QRect(133, 409, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_back.setText(_translate("MainWindow", "<<"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_multiply.setText(_translate("MainWindow", "*"))
        self.pushButton_divide.setText(_translate("MainWindow", "/"))
        self.pushButton_5.setText(_translate("MainWindow", "6"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))


    def result(self):
        try:
            screen=self.outputlabel.text()
            answer=eval(screen)
            if len(str(answer))>11:
                self.outputlabel.setText(str(answer)[:12])
            self.outputlabel.setText(str(answer))
        except:
            self.outputlabel.setText("ERROR")

    def sign(self,s):
        t=self.outputlabel.text()
        if t[-1]==s:
            pass
        else:
            self.outputlabel.setText(self.outputlabel.text()+s)

    def backbutton(self):
        t=self.outputlabel.text()
        self.outputlabel.setText(t[0:-1])

    def pressbutton(self,pressed):
        if pressed=="C":
            self.outputlabel.setText("0")
        else:
            if self.outputlabel.text()=="0":
                self.outputlabel.setText("")
            self.outputlabel.setText(self.outputlabel.text()+pressed)
          
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
